import ServiceCard from "../components/ServiceCard"

function ServicesPage() {
    return (
        <div className="min-h-screen mt-20">
            <h1 className="text-3xl text-center">Our Services</h1>
            <p className="text-center mt-1 text-xl">We provide multiple services.</p>
            <div className="mt-6">

                <ServiceCard heading="Website Creation" description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, incidunt a, temporibus repudiandae ab consequuntur voluptatem quas et magni, non quos nobis neque soluta recusandae vitae dolorum! Voluptas eligendi incidunt culpa porro. Recusandae impedit unde veniam, explicabo sed error, ab, quis vel natus ratione voluptatum sequi? Neque, quis molestias recusandae aperiam dolores reprehenderit doloremque possimus non perspiciatis, labore accusamus, quidem reiciendis dignissimos impedit quos ducimus illum dolorum maiores! Consequuntur error nobis reprehenderit possimus itaque mollitia nulla quos, voluptatibus libero, laudantium perspiciatis aperiam distinctio laboriosam omnis. Consectetur voluptatum est quisquam corporis omnis, incidunt repellendus architecto culpa blanditiis itaque magnam nam eos." bgColor="bg-yellow-600/25" />

                <ServiceCard heading="Graphic Designing" description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, incidunt a, temporibus repudiandae ab consequuntur voluptatem quas et magni, non quos nobis neque soluta recusandae vitae dolorum! Voluptas eligendi incidunt culpa porro. Recusandae impedit unde veniam, explicabo sed error, ab, quis vel natus ratione voluptatum sequi? Neque, quis molestias recusandae aperiam dolores reprehenderit doloremque possimus non perspiciatis, labore accusamus, quidem reiciendis dignissimos impedit quos ducimus illum dolorum maiores! Consequuntur error nobis reprehenderit possimus itaque mollitia nulla quos, voluptatibus libero, laudantium perspiciatis aperiam distinctio laboriosam omnis. Consectetur voluptatum est quisquam corporis omnis, incidunt repellendus architecto culpa blanditiis itaque magnam nam eos." bgColor="bg-blue-600/25" imagePosition="right" />

                <ServiceCard heading="Search Engine Optimization (SEO)" description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, incidunt a, temporibus repudiandae ab consequuntur voluptatem quas et magni, non quos nobis neque soluta recusandae vitae dolorum! Voluptas eligendi incidunt culpa porro. Recusandae impedit unde veniam, explicabo sed error, ab, quis vel natus ratione voluptatum sequi? Neque, quis molestias recusandae aperiam dolores reprehenderit doloremque possimus non perspiciatis, labore accusamus, quidem reiciendis dignissimos impedit quos ducimus illum dolorum maiores! Consequuntur error nobis reprehenderit possimus itaque mollitia nulla quos, voluptatibus libero, laudantium perspiciatis aperiam distinctio laboriosam omnis. Consectetur voluptatum est quisquam corporis omnis, incidunt repellendus architecto culpa blanditiis itaque magnam nam eos." bgColor="bg-green-600/25" />

                <ServiceCard heading="Photography" description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, incidunt a, temporibus repudiandae ab consequuntur voluptatem quas et magni, non quos nobis neque soluta recusandae vitae dolorum! Voluptas eligendi incidunt culpa porro. Recusandae impedit unde veniam, explicabo sed error, ab, quis vel natus ratione voluptatum sequi? Neque, quis molestias recusandae aperiam dolores reprehenderit doloremque possimus non perspiciatis, labore accusamus, quidem reiciendis dignissimos impedit quos ducimus illum dolorum maiores! Consequuntur error nobis reprehenderit possimus itaque mollitia nulla quos, voluptatibus libero, laudantium perspiciatis aperiam distinctio laboriosam omnis. Consectetur voluptatum est quisquam corporis omnis, incidunt repellendus architecto culpa blanditiis itaque magnam nam eos." bgColor="bg-red-600/25" imagePosition="right" />

                <ServiceCard heading="Video Editing" description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, incidunt a, temporibus repudiandae ab consequuntur voluptatem quas et magni, non quos nobis neque soluta recusandae vitae dolorum! Voluptas eligendi incidunt culpa porro. Recusandae impedit unde veniam, explicabo sed error, ab, quis vel natus ratione voluptatum sequi? Neque, quis molestias recusandae aperiam dolores reprehenderit doloremque possimus non perspiciatis, labore accusamus, quidem reiciendis dignissimos impedit quos ducimus illum dolorum maiores! Consequuntur error nobis reprehenderit possimus itaque mollitia nulla quos, voluptatibus libero, laudantium perspiciatis aperiam distinctio laboriosam omnis. Consectetur voluptatum est quisquam corporis omnis, incidunt repellendus architecto culpa blanditiis itaque magnam nam eos." bgColor="bg-amber-600/25" />


            </div>
        </div>
    )
}
export default ServicesPage